// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function AnalyzeProject(projectID: string): $CancellablePromise<models$0.AgentProjectAnalysis | null> {
    return $Call.ByID(1451733442, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ApplyFileEdit(planID: string, typedName: string): $CancellablePromise<models$0.AgentFileEditResult | null> {
    return $Call.ByID(1865183595, planID, typedName).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Chat(req: models$0.AgentChatRequest): $CancellablePromise<models$0.AgentChatResponse | null> {
    return $Call.ByID(3444129041, req).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DraftProjectFile(req: models$0.AgentDraftFileRequest): $CancellablePromise<models$0.AgentDraftFileResponse | null> {
    return $Call.ByID(3291403973, req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ExecuteTool(req: models$0.AgentToolExecutionRequest): $CancellablePromise<models$0.AgentToolResult | null> {
    return $Call.ByID(3643241100, req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function PlanFileEdit(req: models$0.AgentFileEditRequest): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(4074296898, req).then(($result: any) => {
        return $$createType11($result);
    });
}

export function Status(): $CancellablePromise<models$0.AgentStatus | null> {
    return $Call.ByID(3181999705).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ToolCatalog(): $CancellablePromise<models$0.AgentToolSpec[]> {
    return $Call.ByID(2194297540).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.AgentProjectAnalysis.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.AgentFileEditResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.AgentChatResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.AgentDraftFileResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = models$0.AgentToolResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = models$0.CommandPlan.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = models$0.AgentStatus.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = models$0.AgentToolSpec.createFrom;
const $$createType15 = $Create.Array($$createType14);
