// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function ApplyBackup(planID: string): $CancellablePromise<string> {
    return $Call.ByID(2274904588, planID);
}

export function ApplyDeleteBackup(planID: string): $CancellablePromise<void> {
    return $Call.ByID(515387423, planID);
}

export function ApplyRestore(planID: string, typedName: string): $CancellablePromise<string> {
    return $Call.ByID(2356649536, planID, typedName);
}

export function DeleteBackup(backupID: string): $CancellablePromise<void> {
    return $Call.ByID(211269783, backupID);
}

export function ListBackups(filter: models$0.BackupFilter): $CancellablePromise<models$0.BackupSummary[]> {
    return $Call.ByID(149806977, filter).then(($result: any) => {
        return $$createType1($result);
    });
}

export function PlanBackupVolume(req: models$0.BackupVolumeRequest): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(3500563541, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function PlanDeleteBackup(backupID: string): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(3571190712, backupID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function PlanRestoreVolume(req: models$0.RestoreVolumeRequest): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(2302725703, req).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.BackupSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.CommandPlan.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
