// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function DiscoverProjectLineage(projectID: string): $CancellablePromise<models$0.ImageLineage[]> {
    return $Call.ByID(3838558739, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetContainerLineage(containerID: string): $CancellablePromise<models$0.ImageLineage | null> {
    return $Call.ByID(3200582322, containerID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetProjectLineage(projectID: string): $CancellablePromise<models$0.ImageLineage[]> {
    return $Call.ByID(2932089088, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetServiceLineage(projectID: string, service: string): $CancellablePromise<models$0.ImageLineage | null> {
    return $Call.ByID(1624384586, projectID, service).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RefreshServiceLineage(projectID: string, service: string): $CancellablePromise<models$0.ImageLineage | null> {
    return $Call.ByID(2941853753, projectID, service).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.ImageLineage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
