// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function ExportLogs(req: models$0.ExportLogsRequest): $CancellablePromise<models$0.ExportResult | null> {
    return $Call.ByID(322133470, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function FetchLogPage(req: models$0.LogPageRequest): $CancellablePromise<models$0.LogPage | null> {
    return $Call.ByID(3957531718, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StartLogStream(req: models$0.LogStreamRequest): $CancellablePromise<string> {
    return $Call.ByID(3715102761, req);
}

export function StopStream(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(991749095, streamID);
}

// Private type creation functions
const $$createType0 = models$0.ExportResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.LogPage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
