// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function GetStatus(): $CancellablePromise<models$0.PortForwardStatus | null> {
    return $Call.ByID(695079184).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3839660063, enabled);
}

// Private type creation functions
const $$createType0 = models$0.PortForwardStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
