// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function KnownRegistries(): $CancellablePromise<models$0.RegistryPreset[]> {
    return $Call.ByID(572168877).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListRegistryAccounts(): $CancellablePromise<models$0.RegistryAccount[]> {
    return $Call.ByID(262127296).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Login(req: models$0.RegistryLoginRequest): $CancellablePromise<void> {
    return $Call.ByID(1133435360, req);
}

export function Logout(registry: string): $CancellablePromise<void> {
    return $Call.ByID(3439585317, registry);
}

export function TestAuth(registry: string): $CancellablePromise<models$0.RegistryAuthStatus | null> {
    return $Call.ByID(4104214801, registry).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.RegistryPreset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.RegistryAccount.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.RegistryAuthStatus.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
