// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CloseTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4257619016, sessionID);
}

export function DetectContainerShells(containerID: string): $CancellablePromise<string[]> {
    return $Call.ByID(440305753, containerID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListTerminalSessions(): $CancellablePromise<models$0.TerminalSessionInfo[]> {
    return $Call.ByID(3501313961).then(($result: any) => {
        return $$createType2($result);
    });
}

export function OpenBackendTerminal(opts: models$0.TerminalOptions): $CancellablePromise<models$0.TerminalSessionInfo | null> {
    return $Call.ByID(830635268, opts).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenContainerTerminal(containerID: string, opts: models$0.ContainerTerminalOptions): $CancellablePromise<models$0.TerminalSessionInfo | null> {
    return $Call.ByID(2768125935, containerID, opts).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenHostTerminal(opts: models$0.TerminalOptions): $CancellablePromise<models$0.TerminalSessionInfo | null> {
    return $Call.ByID(288046414, opts).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenProjectTerminal(projectID: string, opts: models$0.TerminalOptions): $CancellablePromise<models$0.TerminalSessionInfo | null> {
    return $Call.ByID(70372101, projectID, opts).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ResizeTerminal(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2104460980, sessionID, cols, rows);
}

export function WriteTerminal(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1760068583, sessionID, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.TerminalSessionInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Nullable($$createType1);
