// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function Chat(req: models$0.AgentChatRequest): $CancellablePromise<models$0.AgentChatResponse | null> {
    return $Call.ByID(3444129041, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Status(): $CancellablePromise<models$0.AgentStatus | null> {
    return $Call.ByID(3181999705).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ToolCatalog(): $CancellablePromise<models$0.AgentToolSpec[]> {
    return $Call.ByID(2194297540).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.AgentChatResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.AgentStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.AgentToolSpec.createFrom;
const $$createType5 = $Create.Array($$createType4);
