// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function Config(projectID: string): $CancellablePromise<models$0.ComposeConfigResult | null> {
    return $Call.ByID(1412705912, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Ps(projectID: string): $CancellablePromise<models$0.ComposeServiceStatus[]> {
    return $Call.ByID(3970934603, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RestartServices(projectID: string, services: string[]): $CancellablePromise<void> {
    return $Call.ByID(1949654089, projectID, services);
}

export function ScaleService(projectID: string, service: string, replicas: number): $CancellablePromise<void> {
    return $Call.ByID(473173919, projectID, service, replicas);
}

export function StartServices(projectID: string, services: string[]): $CancellablePromise<void> {
    return $Call.ByID(3294992178, projectID, services);
}

export function StopServices(projectID: string, services: string[]): $CancellablePromise<void> {
    return $Call.ByID(1564832490, projectID, services);
}

// Private type creation functions
const $$createType0 = models$0.ComposeConfigResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ComposeServiceStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
