// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function BulkContainerAction(ids: string[], action: string): $CancellablePromise<models$0.BulkResult | null> {
    return $Call.ByID(169789409, ids, action).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateNetwork(req: models$0.CreateNetworkRequest): $CancellablePromise<models$0.NetworkSummary | null> {
    return $Call.ByID(3605792666, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CreateVolume(req: models$0.CreateVolumeRequest): $CancellablePromise<models$0.VolumeSummary | null> {
    return $Call.ByID(500118806, req).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DiskUsage(): $CancellablePromise<models$0.DiskUsage | null> {
    return $Call.ByID(2345440464).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetContainer(id: string): $CancellablePromise<models$0.ContainerDetail | null> {
    return $Call.ByID(3255901267, id).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetImage(id: string): $CancellablePromise<models$0.ImageDetail | null> {
    return $Call.ByID(975398329, id).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetNetwork(id: string): $CancellablePromise<models$0.NetworkDetail | null> {
    return $Call.ByID(884180562, id).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetVolume(name: string): $CancellablePromise<models$0.VolumeDetail | null> {
    return $Call.ByID(3594940286, name).then(($result: any) => {
        return $$createType15($result);
    });
}

export function Info(): $CancellablePromise<models$0.DockerInfo | null> {
    return $Call.ByID(364380892).then(($result: any) => {
        return $$createType17($result);
    });
}

export function InspectContainerRaw(id: string): $CancellablePromise<string> {
    return $Call.ByID(978203467, id);
}

export function KillContainer(id: string): $CancellablePromise<void> {
    return $Call.ByID(1539714983, id);
}

export function ListContainers(opts: models$0.ContainerListOptions): $CancellablePromise<models$0.ContainerSummary[]> {
    return $Call.ByID(4209014116, opts).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ListImages(): $CancellablePromise<models$0.ImageSummary[]> {
    return $Call.ByID(54024818).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ListNetworks(): $CancellablePromise<models$0.NetworkSummary[]> {
    return $Call.ByID(3981221319).then(($result: any) => {
        return $$createType22($result);
    });
}

export function ListVolumes(): $CancellablePromise<models$0.VolumeSummary[]> {
    return $Call.ByID(4113921307).then(($result: any) => {
        return $$createType23($result);
    });
}

export function LoadImage(srcPath: string): $CancellablePromise<string> {
    return $Call.ByID(2286805465, srcPath);
}

export function Ping(): $CancellablePromise<void> {
    return $Call.ByID(1987249976);
}

export function PlanPrune(kind: string): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(3091027417, kind).then(($result: any) => {
        return $$createType25($result);
    });
}

export function PlanRemoveContainer(id: string, opts: models$0.RemoveContainerOptions): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(783154554, id, opts).then(($result: any) => {
        return $$createType25($result);
    });
}

export function PlanRemoveImage(imageID: string, force: boolean): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(590018692, imageID, force).then(($result: any) => {
        return $$createType25($result);
    });
}

export function PlanRemoveNetwork(id: string): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(3243822551, id).then(($result: any) => {
        return $$createType25($result);
    });
}

export function PlanRemoveVolume(name: string, force: boolean): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(1592087289, name, force).then(($result: any) => {
        return $$createType25($result);
    });
}

export function PullImage(imageRef: string): $CancellablePromise<string> {
    return $Call.ByID(1735976676, imageRef);
}

export function PushImage(imageRef: string): $CancellablePromise<string> {
    return $Call.ByID(3287037137, imageRef);
}

export function RenameContainer(id: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1466090241, id, newName);
}

export function RestartContainer(id: string, timeoutSeconds: number): $CancellablePromise<void> {
    return $Call.ByID(4010310214, id, timeoutSeconds);
}

export function RunImage(req: models$0.RunImageRequest): $CancellablePromise<string> {
    return $Call.ByID(597124842, req);
}

export function SaveImage(imageRefs: string[], destPath: string): $CancellablePromise<string> {
    return $Call.ByID(313546242, imageRefs, destPath);
}

export function SearchHub(query: string, limit: number): $CancellablePromise<models$0.HubSearchResult[]> {
    return $Call.ByID(3553985035, query, limit).then(($result: any) => {
        return $$createType27($result);
    });
}

export function StartContainer(id: string): $CancellablePromise<void> {
    return $Call.ByID(1838528435, id);
}

export function StopContainer(id: string, timeoutSeconds: number): $CancellablePromise<void> {
    return $Call.ByID(1752754799, id, timeoutSeconds);
}

export function TagImage(imageID: string, newRef: string): $CancellablePromise<void> {
    return $Call.ByID(3662517405, imageID, newRef);
}

export function Version(): $CancellablePromise<models$0.DockerVersion | null> {
    return $Call.ByID(2954904332).then(($result: any) => {
        return $$createType29($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.BulkResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.NetworkSummary.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.VolumeSummary.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.DiskUsage.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = models$0.ContainerDetail.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = models$0.ImageDetail.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = models$0.NetworkDetail.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = models$0.VolumeDetail.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = models$0.DockerInfo.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = models$0.ContainerSummary.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = models$0.ImageSummary.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Array($$createType2);
const $$createType23 = $Create.Array($$createType4);
const $$createType24 = models$0.CommandPlan.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = models$0.HubSearchResult.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = models$0.DockerVersion.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
