// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BackupService from "./backupservice.js";
import * as ComposeService from "./composeservice.js";
import * as DockerService from "./dockerservice.js";
import * as ImageLineageService from "./imagelineageservice.js";
import * as LogsService from "./logsservice.js";
import * as MetricsService from "./metricsservice.js";
import * as ProjectService from "./projectservice.js";
import * as ProviderService from "./providerservice.js";
import * as RegistryService from "./registryservice.js";
import * as SettingsService from "./settingsservice.js";
import * as TerminalService from "./terminalservice.js";
import * as UpdateService from "./updateservice.js";
export {
    BackupService,
    ComposeService,
    DockerService,
    ImageLineageService,
    LogsService,
    MetricsService,
    ProjectService,
    ProviderService,
    RegistryService,
    SettingsService,
    TerminalService,
    UpdateService
};
