// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function GetContainerMetrics(containerID: string, r: models$0.TimeRange): $CancellablePromise<models$0.SeriesBundle | null> {
    return $Call.ByID(3200869941, containerID, r).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetDashboardMetrics(): $CancellablePromise<models$0.DashboardMetrics | null> {
    return $Call.ByID(4233896820).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetProjectMetrics(projectID: string, r: models$0.TimeRange): $CancellablePromise<models$0.SeriesBundle | null> {
    return $Call.ByID(4269150979, projectID, r).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartStatsStream(scope: models$0.StatsScope): $CancellablePromise<string> {
    return $Call.ByID(48603856, scope);
}

export function StopStream(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(3097120307, streamID);
}

// Private type creation functions
const $$createType0 = models$0.SeriesBundle.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.DashboardMetrics.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
