// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function GetProject(projectID: string): $CancellablePromise<models$0.ProjectDetail | null> {
    return $Call.ByID(595764834, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportProject(req: models$0.ImportProjectRequest): $CancellablePromise<models$0.ProjectDetail | null> {
    return $Call.ByID(3126173247, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListProjects(): $CancellablePromise<models$0.ProjectSummary[]> {
    return $Call.ByID(1261700661).then(($result: any) => {
        return $$createType3($result);
    });
}

export function PlanDownProject(projectID: string, removeVolumes: boolean): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(2130027865, projectID, removeVolumes).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PlanRedeployProject(projectID: string): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(2512814603, projectID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PullProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3862228645, projectID);
}

export function RefreshProjects(): $CancellablePromise<models$0.ProjectSummary[]> {
    return $Call.ByID(2709840416).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RemoveProjectFromList(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3587169416, projectID);
}

export function RestartProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3364293751, projectID);
}

export function StartProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1592654942, projectID);
}

export function StopProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(311498564, projectID);
}

// Private type creation functions
const $$createType0 = models$0.ProjectDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ProjectSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.CommandPlan.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
