// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function ApplyInstall(planID: string): $CancellablePromise<models$0.InstallProgressHandle | null> {
    return $Call.ByID(1257602498, planID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ApplyProviderPlan(planID: string, typedName: string): $CancellablePromise<void> {
    return $Call.ByID(3550597673, planID, typedName);
}

export function Detect(providerID: string): $CancellablePromise<models$0.ProviderStatus | null> {
    return $Call.ByID(2594388346, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DetectAll(): $CancellablePromise<{ [_ in string]?: models$0.ProviderStatus | null }> {
    return $Call.ByID(1325877761).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetProvider(providerID: string): $CancellablePromise<models$0.ProviderDetail | null> {
    return $Call.ByID(2020513694, providerID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListDockerContexts(): $CancellablePromise<models$0.DockerContextInfo[]> {
    return $Call.ByID(157753513).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListProviders(): $CancellablePromise<models$0.ProviderSummary[]> {
    return $Call.ByID(4260401113).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListWSLDistros(): $CancellablePromise<models$0.WSLDistroInfo[]> {
    return $Call.ByID(650548699).then(($result: any) => {
        return $$createType12($result);
    });
}

export function PlanInstall(providerID: string, opts: models$0.InstallOptions): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(1372038617, providerID, opts).then(($result: any) => {
        return $$createType14($result);
    });
}

export function PlanRestart(providerID: string): $CancellablePromise<models$0.CommandPlan | null> {
    return $Call.ByID(1935115277, providerID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function Restart(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(3893040676, providerID);
}

export function SetActiveProvider(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(229778316, providerID);
}

export function SetDockerContext(name: string): $CancellablePromise<void> {
    return $Call.ByID(256096338, name);
}

export function Start(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(1386500759, providerID);
}

export function Stop(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(1617116029, providerID);
}

// Private type creation functions
const $$createType0 = models$0.InstallProgressHandle.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ProviderStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = models$0.ProviderDetail.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = models$0.DockerContextInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.ProviderSummary.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = models$0.WSLDistroInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = models$0.CommandPlan.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
