// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function ApplyUpdate(req: models$0.ApplyUpdateRequest): $CancellablePromise<string> {
    return $Call.ByID(2969046818, req);
}

export function CheckAllUpdates(): $CancellablePromise<string> {
    return $Call.ByID(3172433760);
}

export function CheckProjectUpdates(projectID: string): $CancellablePromise<models$0.ImageUpdate[]> {
    return $Call.ByID(1025649146, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CheckServiceUpdate(projectID: string, service: string): $CancellablePromise<models$0.ImageUpdate | null> {
    return $Call.ByID(3527487467, projectID, service).then(($result: any) => {
        return $$createType2($result);
    });
}

export function IgnoreUpdate(req: models$0.IgnoreUpdateRequest): $CancellablePromise<void> {
    return $Call.ByID(3722831530, req);
}

export function ListCurrentUpdates(filter: models$0.UpdateFilter): $CancellablePromise<models$0.ImageUpdate[]> {
    return $Call.ByID(1290489764, filter).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListUpdateHistory(filter: models$0.UpdateHistoryFilter): $CancellablePromise<models$0.UpdateHistoryItem[]> {
    return $Call.ByID(1871912704, filter).then(($result: any) => {
        return $$createType4($result);
    });
}

export function PlanProjectUpdate(projectID: string): $CancellablePromise<models$0.UpdatePlan | null> {
    return $Call.ByID(3794215738, projectID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function PlanServiceUpdate(projectID: string, service: string): $CancellablePromise<models$0.UpdatePlan | null> {
    return $Call.ByID(1485836880, projectID, service).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Rollback(historyID: number): $CancellablePromise<string> {
    return $Call.ByID(2168820661, historyID);
}

export function UnignoreUpdate(id: number): $CancellablePromise<void> {
    return $Call.ByID(3277431445, id);
}

// Private type creation functions
const $$createType0 = models$0.ImageUpdate.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
const $$createType3 = models$0.UpdateHistoryItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = models$0.UpdatePlan.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
