package terminal

import "github.com/RCooLeR/Cairn/internal/models"

func CheatsheetEntries() []models.CheatsheetEntry {
	entries := []models.CheatsheetEntry{
		{Category: "containers", Command: "docker ps", Description: "List running containers", Risk: models.RiskSafe, Runnable: true},
		{Category: "containers", Command: "docker ps -a", Description: "List all containers", Risk: models.RiskSafe, Runnable: true},
		{Category: "containers", Command: "docker inspect <container>", Description: "Inspect one container", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "containers", Command: "docker top <container>", Description: "Show container processes", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "containers", Command: "docker port <container>", Description: "Show published ports", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "containers", Command: "docker stats --no-stream <container>", Description: "Show one-shot container usage", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "containers", Command: "docker start <container>", Description: "Start a stopped container", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "containers", Command: "docker stop <container>", Description: "Stop a running container", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "containers", Command: "docker restart <container>", Description: "Restart a running container", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "containers", Command: "docker rename <container> <name>", Description: "Rename a container", Risk: models.RiskSafe, Placeholders: []string{"container", "name"}, Runnable: true},
		{Category: "containers", Command: "docker run -d --name <name> <image>", Description: "Run an image as a detached container", Risk: models.RiskSafe, Placeholders: []string{"name", "image"}, Runnable: true},
		{Category: "containers", Command: "docker kill <container>", Description: "Kill a running container", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"container"}},
		{Category: "containers", Command: "docker rm <container>", Description: "Remove a stopped container", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"container"}},
		{Category: "containers", Command: "docker rm -f <container>", Description: "Force remove a running container", Risk: models.RiskDestructive, Placeholders: []string{"container"}},
		{Category: "images", Command: "docker images", Description: "List local images", Risk: models.RiskSafe, Runnable: true},
		{Category: "images", Command: "docker image ls --digests", Description: "List images with digests", Risk: models.RiskSafe, Runnable: true},
		{Category: "images", Command: "docker image inspect <image>", Description: "Inspect one image", Risk: models.RiskSafe, Placeholders: []string{"image"}, Runnable: true},
		{Category: "images", Command: "docker history <image>", Description: "Show image layer history", Risk: models.RiskSafe, Placeholders: []string{"image"}, Runnable: true},
		{Category: "images", Command: "docker manifest inspect <image>", Description: "Inspect a remote image manifest", Risk: models.RiskSafe, Placeholders: []string{"image"}, Runnable: true},
		{Category: "images", Command: "docker pull <image>", Description: "Pull an image", Risk: models.RiskSafe, Placeholders: []string{"image"}, Runnable: true},
		{Category: "images", Command: "docker tag <image> <target>", Description: "Tag an image reference", Risk: models.RiskSafe, Placeholders: []string{"image", "target"}, Runnable: true},
		{Category: "images", Command: "docker save -o <path> <image>", Description: "Save an image to a tar archive", Risk: models.RiskSafe, Placeholders: []string{"path", "image"}, Runnable: true},
		{Category: "images", Command: "docker load -i <path>", Description: "Load an image tar archive", Risk: models.RiskSafe, Placeholders: []string{"path"}, Runnable: true},
		{Category: "images", Command: "docker push <image>", Description: "Push an image to a registry", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"image"}},
		{Category: "images", Command: "docker rmi <image>", Description: "Remove an unused image", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"image"}},
		{Category: "images", Command: "docker rmi -f <image>", Description: "Force remove an image used by containers", Risk: models.RiskDestructive, Placeholders: []string{"image"}},
		{Category: "compose", Command: "docker compose ps", Description: "List Compose project containers", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose config", Description: "Render effective Compose config", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose ls", Description: "List known Compose projects", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose logs --tail=100", Description: "Show recent Compose logs", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose top", Description: "Show Compose service processes", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose pull <service>", Description: "Pull the image for one service", Risk: models.RiskSafe, Placeholders: []string{"service"}, Runnable: true},
		{Category: "compose", Command: "docker compose start", Description: "Start a stopped Compose project", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose stop", Description: "Stop a running Compose project", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose restart", Description: "Restart a Compose project", Risk: models.RiskSafe, Runnable: true},
		{Category: "compose", Command: "docker compose up -d <service>", Description: "Create or update a service", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"service"}},
		{Category: "compose", Command: "docker compose build --pull <service>", Description: "Rebuild a service from a fresh base image", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"service"}},
		{Category: "compose", Command: "docker compose up -d --force-recreate <service>", Description: "Force recreate one service", Risk: models.RiskDestructive, Placeholders: []string{"service"}},
		{Category: "compose", Command: "docker compose down", Description: "Stop and remove project containers/networks", Risk: models.RiskDestructive},
		{Category: "compose", Command: "docker compose down --volumes", Description: "Remove project containers, networks, and volumes", Risk: models.RiskDangerous},
		{Category: "volumes", Command: "docker volume ls", Description: "List volumes", Risk: models.RiskSafe, Runnable: true},
		{Category: "volumes", Command: "docker volume inspect <volume>", Description: "Inspect one volume", Risk: models.RiskSafe, Placeholders: []string{"volume"}, Runnable: true},
		{Category: "volumes", Command: "docker volume create <volume>", Description: "Create a named volume", Risk: models.RiskSafe, Placeholders: []string{"volume"}, Runnable: true},
		{Category: "volumes", Command: "docker run --rm -v <volume>:/data:ro busybox du -sh /data", Description: "Estimate volume usage read-only", Risk: models.RiskSafe, Placeholders: []string{"volume"}, Runnable: true},
		{Category: "volumes", Command: "docker volume rm <volume>", Description: "Delete a named volume", Risk: models.RiskDangerous, Placeholders: []string{"volume"}},
		{Category: "volumes", Command: "docker volume prune", Description: "Remove unused volumes", Risk: models.RiskDangerous},
		{Category: "networks", Command: "docker network ls", Description: "List networks", Risk: models.RiskSafe, Runnable: true},
		{Category: "networks", Command: "docker network inspect <network>", Description: "Inspect one network", Risk: models.RiskSafe, Placeholders: []string{"network"}, Runnable: true},
		{Category: "networks", Command: "docker network inspect bridge", Description: "Inspect default bridge network", Risk: models.RiskSafe, Runnable: true},
		{Category: "networks", Command: "docker network create <network>", Description: "Create a bridge network", Risk: models.RiskSafe, Placeholders: []string{"network"}, Runnable: true},
		{Category: "networks", Command: "docker network rm <network>", Description: "Remove a network", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"network"}},
		{Category: "logs", Command: "docker logs --tail=100 <container>", Description: "Show recent logs", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "logs", Command: "docker logs -f --tail=100 <container>", Description: "Follow logs", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "logs", Command: "docker logs --since=10m <container>", Description: "Show recent time-window logs", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "logs", Command: "docker compose logs --tail=100 <service>", Description: "Show recent service logs", Risk: models.RiskSafe, Placeholders: []string{"service"}, Runnable: true},
		{Category: "logs", Command: "docker compose logs -f --tail=100 <service>", Description: "Follow service logs", Risk: models.RiskSafe, Placeholders: []string{"service"}, Runnable: true},
		{Category: "logs", Command: "docker events --since 10m", Description: "Watch recent Docker events", Risk: models.RiskSafe, Runnable: true},
		{Category: "exec", Command: "docker exec -it <container> /bin/sh", Description: "Open a shell in a container", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "exec", Command: "docker exec -it <container> /bin/bash", Description: "Open bash when the image has it", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "exec", Command: "docker exec <container> id", Description: "Print active exec user", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "exec", Command: "docker exec <container> pwd", Description: "Print container working directory", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "exec", Command: "docker exec <container> ls -la", Description: "List container working directory", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "exec", Command: "docker exec <container> df -h", Description: "Show container filesystem usage", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "exec", Command: "docker exec <container> cat /etc/os-release", Description: "Show container OS release", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "exec", Command: "docker exec -u root -it <container> /bin/sh", Description: "Open a root shell explicitly", Risk: models.RiskNeedsConfirmation, Placeholders: []string{"container"}},
		{Category: "stats/debug", Command: "docker stats --no-stream", Description: "One-shot resource usage", Risk: models.RiskSafe, Runnable: true},
		{Category: "stats/debug", Command: "docker stats <container>", Description: "Stream container resource usage", Risk: models.RiskSafe, Placeholders: []string{"container"}, Runnable: true},
		{Category: "stats/debug", Command: "docker system df", Description: "Show Docker disk usage", Risk: models.RiskSafe, Runnable: true},
		{Category: "stats/debug", Command: "docker system df -v", Description: "Show detailed Docker disk usage", Risk: models.RiskSafe, Runnable: true},
		{Category: "stats/debug", Command: "docker system info", Description: "Show daemon information", Risk: models.RiskSafe, Runnable: true},
		{Category: "stats/debug", Command: "docker version", Description: "Show client and server versions", Risk: models.RiskSafe, Runnable: true},
		{Category: "stats/debug", Command: "docker context ls", Description: "List Docker contexts", Risk: models.RiskSafe, Runnable: true},
		{Category: "stats/debug", Command: "docker compose version", Description: "Show Compose plugin version", Risk: models.RiskSafe, Runnable: true},
		{Category: "cleanup", Command: "docker builder du", Description: "Preview build cache usage", Risk: models.RiskSafe, Runnable: true},
		{Category: "cleanup", Command: "docker container prune", Description: "Prune stopped containers", Risk: models.RiskDestructive},
		{Category: "cleanup", Command: "docker image prune", Description: "Prune dangling images", Risk: models.RiskDestructive},
		{Category: "cleanup", Command: "docker image prune -a", Description: "Prune all unused images", Risk: models.RiskDestructive},
		{Category: "cleanup", Command: "docker builder prune", Description: "Prune build cache", Risk: models.RiskDestructive},
		{Category: "cleanup", Command: "docker system prune", Description: "Remove unused Docker data", Risk: models.RiskDangerous},
		{Category: "cleanup", Command: "docker system prune --volumes", Description: "Remove unused Docker data including volumes", Risk: models.RiskDangerous},
	}
	return append([]models.CheatsheetEntry(nil), entries...)
}
